import { ArrowLeft, CalendarDays, Camera, FilePenLine, FilePlus2, FolderOpen, Plus, Save, Trash2, X } from "lucide-react";
import { ChangeEvent, useEffect, useState } from "react";

export type Investigation = { id:string; title:string; status:"OUVERTE"|"EN COURS"|"CLASSÉE"; description:string; updatedAt:string };
type ImageItem = { name:string; dataUrl:string };
type Section = { id:string; title:string; description:string; images:ImageItem[] };
type Report = { id:string; title:string; reportDate:string; details:string; content:{ images:ImageItem[]; sections:Section[] } };
type ReportForm = { title:string; reportDate:string; details:string; images:ImageItem[]; sections:Section[] };
type Request = (path:string, options?:RequestInit) => Promise<any>;

const emptyReport = ():ReportForm => ({ title:"", reportDate:new Date().toISOString().slice(0,10), details:"", images:[], sections:[] });
const newSection = ():Section => ({ id:crypto.randomUUID(), title:"", description:"", images:[] });

async function optimizeImage(file:File):Promise<ImageItem>{
  if(!file.type.startsWith("image/")) throw new Error("Seules les images sont acceptées");
  if(file.size>15_000_000) throw new Error("Une image ne peut pas dépasser 15 Mo");
  const source=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});
  const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=source});
  const scale=Math.min(1,1600/Math.max(image.width,image.height));
  const canvas=document.createElement("canvas");canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);
  canvas.getContext("2d")!.drawImage(image,0,0,canvas.width,canvas.height);
  return {name:file.name,dataUrl:canvas.toDataURL("image/jpeg",.82)};
}

export function InvestigationView({investigation,request,onBack,onEdit}:{investigation:Investigation;request:Request;onBack:()=>void;onEdit:()=>void}){
  const [reports,setReports]=useState<Report[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [editor,setEditor]=useState<ReportForm|null>(null); const [editingId,setEditingId]=useState<string>(); const [saving,setSaving]=useState(false);
  const load=async()=>{setLoading(true);try{const data=await request(`/investigations/${investigation.id}/reports`);setReports(data.map((r:Report)=>({...r,content:r.content||{images:[],sections:[]}})));setError("")}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
  useEffect(()=>{void load()},[investigation.id]);
  const openEditor=(report?:Report)=>{setEditingId(report?.id);setEditor(report?{title:report.title,reportDate:report.reportDate.slice(0,10),details:report.details,images:report.content.images||[],sections:(report.content.sections||[]).map(s=>({...s,id:s.id||crypto.randomUUID()}))}:emptyReport());setError("")};
  const save=async()=>{if(!editor)return;setSaving(true);try{await request(`/investigations/${investigation.id}/reports${editingId?`/${editingId}`:""}`,{method:editingId?"PUT":"POST",body:JSON.stringify(editor)});setEditor(null);await load()}catch(e){setError((e as Error).message)}finally{setSaving(false)}};
  const remove=async(id:string)=>{if(!confirm("Supprimer définitivement ce rapport ?"))return;await request(`/investigations/${investigation.id}/reports/${id}`,{method:"DELETE"});await load()};
  const addImages=async(event:ChangeEvent<HTMLInputElement>,target:"report"|number)=>{if(!editor||!event.target.files)return;try{const images=await Promise.all(Array.from(event.target.files).map(optimizeImage));if(target==="report")setEditor({...editor,images:[...editor.images,...images]});else{const sections=[...editor.sections];sections[target]={...sections[target],images:[...sections[target].images,...images]};setEditor({...editor,sections})}}catch(e){setError((e as Error).message)}event.target.value=""};
  const updateSection=(index:number,patch:Partial<Section>)=>{if(!editor)return;const sections=[...editor.sections];sections[index]={...sections[index],...patch};setEditor({...editor,sections})};
  return <div className="case-page">
    <div className="case-page-top"><button className="back-button" onClick={onBack}><ArrowLeft/> Dossiers</button><button className="secondary" onClick={onEdit}><FilePenLine/> Modifier le dossier</button></div>
    <section className={`case-hero status-${investigation.status.replace(" ","-").toLowerCase()}`}><div><span className="case-status">{investigation.status}</span><h1>{investigation.title}</h1><p>{investigation.description||"Aucun résumé renseigné."}</p></div><button className="primary" onClick={()=>openEditor()}><FilePlus2/> Nouveau rapport</button></section>
    <div className="reports-heading"><div><FolderOpen/><h2>Rapports</h2></div><span>{reports.length} rapport{reports.length>1?"s":""}</span></div>
    {error&&<p className="error">{error}</p>}{loading?<div className="empty"><p>Chargement des rapports…</p></div>:!reports.length?<div className="empty"><FilePlus2/><p>Aucun rapport dans ce dossier.</p><button className="primary" onClick={()=>openEditor()}>Créer le premier rapport</button></div>:<div className="reports-list">{reports.map(report=><article className="report" key={report.id}><header><div><span><CalendarDays/> {new Date(report.reportDate).toLocaleDateString("fr-FR")}</span><h2>{report.title}</h2></div><div className="report-actions"><button className="icon" onClick={()=>openEditor(report)} aria-label="Modifier"><FilePenLine/></button><button className="icon danger" onClick={()=>void remove(report.id)} aria-label="Supprimer"><Trash2/></button></div></header>{report.details&&<p className="report-details">{report.details}</p>}<ImageGallery images={report.content.images||[]}/>{(report.content.sections||[]).map((section,index)=><section className="report-section" key={section.id||index}><span>PARAGRAPHE {index+1}</span><h3>{section.title}</h3><p>{section.description}</p><ImageGallery images={section.images||[]}/></section>)}</article>)}</div>}
    {editor&&<div className="overlay" onMouseDown={()=>setEditor(null)}><section className="modal report-editor" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setEditor(null)}><X/></button><p className="eyebrow">{editingId?"MODIFIER LE RAPPORT":"NOUVEAU RAPPORT"}</p><h2>Rapport d’enquête</h2><div className="form-grid"><label>Titre<input value={editor.title} onChange={e=>setEditor({...editor,title:e.target.value})}/></label><label>Date<input type="date" value={editor.reportDate} onChange={e=>setEditor({...editor,reportDate:e.target.value})}/></label><label className="wide">Détails généraux<textarea rows={4} value={editor.details} onChange={e=>setEditor({...editor,details:e.target.value})}/></label><ImageInput label="Images générales" images={editor.images} onFiles={e=>void addImages(e,"report")} onRemove={i=>setEditor({...editor,images:editor.images.filter((_,n)=>n!==i)})}/></div><div className="sections-editor"><div className="sections-title"><h3>Paragraphes du rapport</h3><button className="secondary" onClick={()=>setEditor({...editor,sections:[...editor.sections,newSection()]})}><Plus/> Ajouter un paragraphe</button></div>{!editor.sections.length&&<p className="muted">Ajoutez autant de paragraphes que nécessaire.</p>}{editor.sections.map((section,index)=><section className="section-editor" key={section.id}><div className="section-number">Paragraphe {index+1}<button className="icon danger" onClick={()=>setEditor({...editor,sections:editor.sections.filter((_,n)=>n!==index)})}><Trash2/></button></div><label>Titre<input value={section.title} onChange={e=>updateSection(index,{title:e.target.value})}/></label><label>Description<textarea rows={5} value={section.description} onChange={e=>updateSection(index,{description:e.target.value})}/></label><ImageInput label="Images du paragraphe" images={section.images} onFiles={e=>void addImages(e,index)} onRemove={i=>updateSection(index,{images:section.images.filter((_,n)=>n!==i)})}/></section>)}</div>{error&&<p className="error">{error}</p>}<button className="primary save-report" disabled={saving||!editor.title.trim()||editor.sections.some(s=>!s.title.trim())} onClick={()=>void save()}><Save/> {saving?"Enregistrement…":"Enregistrer le rapport"}</button></section></div>}
  </div>
}

function ImageGallery({images}:{images:ImageItem[]}){return images.length?<div className="image-gallery">{images.map((image,index)=><a href={image.dataUrl} target="_blank" rel="noreferrer" key={`${image.name}-${index}`}><img src={image.dataUrl} alt={image.name}/></a>)}</div>:null}
function ImageInput({label,images,onFiles,onRemove}:{label:string;images:ImageItem[];onFiles:(e:ChangeEvent<HTMLInputElement>)=>void;onRemove:(index:number)=>void}){return <div className="image-input wide"><span>{label}</span><label className="image-add"><Camera/> Ajouter des images<input type="file" accept="image/*" multiple onChange={onFiles}/></label>{images.length>0&&<div className="image-previews">{images.map((image,index)=><div key={`${image.name}-${index}`}><img src={image.dataUrl} alt=""/><button onClick={()=>onRemove(index)} aria-label="Retirer"><X/></button></div>)}</div>}</div>}
